FROM golang:1.19

ENV BIN_FILE /authentication
ENV CODE_DIR /go/src/

WORKDIR ${CODE_DIR}

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

COPY ./ ${CODE_DIR}

RUN CGO_ENABLED=0 go build \
        -o ${BIN_FILE} ./cmd/authentication/*

EXPOSE 8000

CMD ${BIN_FILE}